In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neural_network import MLPClassifier

# Upload and read dataset
df = pd.read_csv('heart.csv')
print(f"Dataset shape: {df.shape}")

# Normalize predictors
target_column = 'target'
predictors = [col for col in df.columns if col != target_column]
df[predictors] = df[predictors] / df[predictors].max()

# Split data
X = df[predictors].values
y = df[target_column].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=40)
print(f"Training shape: {X_train.shape} | Testing shape: {X_test.shape}")

# Function to train and evaluate MLPClassifier
def train_and_evaluate(activation, hidden_layers=(8,8,8), max_iter=500):
    print(f"\nTraining with activation='{activation}' and hidden_layers={hidden_layers}")
    mlp = MLPClassifier(hidden_layer_sizes=hidden_layers, activation=activation,
                        solver='adam', max_iter=max_iter, random_state=42)
    mlp.fit(X_train, y_train)

    predict_train = mlp.predict(X_train)
    predict_test = mlp.predict(X_test)

    print("\nTrain Results:")
    print(confusion_matrix(y_train, predict_train))
    print(classification_report(y_train, predict_train, zero_division=0))

    print("\nTest Results:")
    print(confusion_matrix(y_test, predict_test))
    print(classification_report(y_test, predict_test, zero_division=0))


# Try different activation functions
for activation in ['relu', 'identity', 'tanh', 'logistic']:
    train_and_evaluate(activation)

# Try different hidden layer configuration
train_and_evaluate('relu', hidden_layers=(10,10,10))


Dataset shape: (303, 14)
Training shape: (212, 13) | Testing shape: (91, 13)

Training with activation='relu' and hidden_layers=(8, 8, 8)

Train Results:
[[ 71  27]
 [ 13 101]]
              precision    recall  f1-score   support

           0       0.85      0.72      0.78        98
           1       0.79      0.89      0.83       114

    accuracy                           0.81       212
   macro avg       0.82      0.81      0.81       212
weighted avg       0.82      0.81      0.81       212


Test Results:
[[34  6]
 [ 5 46]]
              precision    recall  f1-score   support

           0       0.87      0.85      0.86        40
           1       0.88      0.90      0.89        51

    accuracy                           0.88        91
   macro avg       0.88      0.88      0.88        91
weighted avg       0.88      0.88      0.88        91


Training with activation='identity' and hidden_layers=(8, 8, 8)

Train Results:
[[ 69  29]
 [ 14 100]]
              precision    reca

In [3]:
X_train

array([[0.7012987 , 1.        , 0.66666667, ..., 0.        , 0.25      ,
        0.66666667],
       [0.67532468, 1.        , 0.        , ..., 1.        , 0.25      ,
        0.66666667],
       [0.83116883, 1.        , 0.        , ..., 0.5       , 0.25      ,
        1.        ],
       ...,
       [0.87012987, 1.        , 0.        , ..., 0.5       , 0.75      ,
        0.66666667],
       [0.57142857, 1.        , 0.33333333, ..., 1.        , 0.        ,
        1.        ],
       [0.62337662, 1.        , 0.        , ..., 1.        , 0.5       ,
        1.        ]])